### ISSUE TITLE
emoji is displayed in <img> under obsidian editor "view" mode

### ISSUE THREAD

**Issue by ClaudiaSmily** [duoani/obsidian-habit-tracker#5]
Hi there,

I try to use this awesome plugin and track my habbit. It works perfect creating the calendar view.
While when displaying the content in "View" mode, the "tag" (or emoji) i am using is wrapped in <img>.

![image](https://user-images.githubusercontent.com/15938536/130379045-49bfea7e-896d-4f54-8976-c70836029998.png)
![image](https://user-images.githubusercontent.com/15938536/130379060-4875bdab-9443-44fa-bf44-a710253a6d4c.png)

May i know is it related with the theme i am using or any other settings?

Thanks!

**Comment by duoani** [comment]
No related theme is required.

For some security reasons (DOM injection attacks), habit tracker plugin does not translate your inputs into HTML tags. That's why the raw HTML **<img draggable="false" ...** appears.

You can try using the origin emoji rather than twitter one.

**Comment by ClaudiaSmily** [comment]
> No related theme is required.
> 
> For some security reasons (DOM injection attacks), habit tracker plugin does not translate your inputs into HTML tags. That's why the raw HTML **<img draggable="false" ...** appears.
> 
> You can try using the origin emoji rather than twitter one.

Oh, I disable "Emoji Toolbar" and everything works fine!
![image](https://user-images.githubusercontent.com/15938536/130885882-1cfce9e4-3ce1-4f21-a689-8396dad22480.png)

**Comment by duoani** [comment]
Emoji Toolbar 很好，我也在用，不需要完全禁用它，只要禁用它的 Twitter Emoji 就好了

**Comment by ClaudiaSmily** [comment]
> Emoji Toolbar 很好，我也在用，不需要完全禁用它，只要禁用它的 Twitter Emoji 就好了

哇！管用！好评！

**Comment by duoani** [comment]
更新到 v1.0.4 后，同时开启本插件的 `Enable HTML` 配置项，就可以支持 Twitter Emoji 了。
@ClaudiaSmily
