### ISSUE TITLE
Emoji are not displayed correctly

### ISSUE THREAD

**Issue by v-rogg** [duoani/obsidian-habit-tracker#6]
Hello, thank you for your work.

I noticed that emojis aren't working for me.
I get the following result using your example.

![CaptureV](https://user-images.githubusercontent.com/20977815/133078554-35abba4a-c8eb-4ee0-8811-509b4cba1054.PNG)

Best regards :)

**Comment by duoani** [comment]
I think you may have installed the "Emoji Toolbar". This plugin has a default configuration that using twitter emojis instead of plain text emojis. Please temporarily  disable this config. I will push a fixed version this days.

**Comment by v-rogg** [comment]
You are right. Simply disabling the Twitter emojis fixed it. Thanks for the quick reply.

**Comment by duoani** [comment]
For supporting Twitter emojis, please update the Habit Tracker plugin to v1.0.4, also, you must enable the configuration `Enable HTML` in this plugin. @v-rogg ^p^

**Comment by v-rogg** [comment]
Thanks, works like a charm
